{
 "title": "VF dbMonitor",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Relative",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Session", "label": "sid", "query": "label_values(top_ses,sid)" },
   {
    "name": "Target",
    "query": "label_values(online_mode,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Time",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "DB Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "online_mode{metric=\"mode\",instance=~\"$Target.*\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Rss Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rss_is_alive{metric=\"rss_is_alive\",instance=~\"$Target.*\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "RSS Gaps",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rss_gaps{instance=~\"$Target.*\"}",
     "legendFormat": "gaps"
    }
   ]
  },
  {
   "title": "Unbak Log",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "unbak_log_num{metric=\"unbak_log_num\",instance=~\"$Target.*\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "User Connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "user_conn{instance=~\"$Target.*\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptime{instance=~\"$Target.*\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Oninit Process",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oninit_num{instance=~\"$Target.*\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "AF File",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "af_num{instance=~\"$Target.*\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "SHM Dump File",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "shmdmp_num{instance=~\"$Target.*\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Connect Time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "conn_time{instance=~\"$Target.*\"}/1024/1024",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Blocked",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blocked{instance=~\"$Target.*\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Important Log",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 200 },
       "type": "raw_document"
      }
     ],
     "query": "_index:filebeat-$Target-*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Failed AUS Command",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 10 },
       "type": "raw_document"
      }
     ],
     "query": "_index:topAusMisson-$Target-* AND aus_cmd_state:E",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Online Mode",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "online_mode{instance=~\"$Target.*\"}",
     "legendFormat": "online_mode"
    }
   ]
  },
  {
   "title": "RSS Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rss_is_alive{instance=~\"$Target.*\"}",
     "legendFormat": "alive"
    }
   ]
  },
  {
   "title": "Rss Gaps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rss_gaps{instance=~\"$Target.*\"}",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "UnBak Logical Log",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "unbak_log_num{instance=~\"$Target.*\"}",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "OB Connection",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "user_conn{instance=~\"$Target.*\"}\n",
     "legendFormat": "connected"
    },
    {
     "expr": "wt_ses_num{instance=~\"$Target.*\"}",
     "legendFormat": "waiting"
    },
    {
     "expr": "stk_ovflow{instance=~\"$Target.*\"}",
     "legendFormat": "overflow"
    }
   ]
  },
  {
   "title": "Virtual Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "vm_usage{metric=\"vm_used\",instance=~\"$Target.*\"}",
     "legendFormat": "used"
    },
    {
     "expr": "vm_usage{metric=\"vm_tot\",instance=~\"$Target.*\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Transaction Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "delta(instance_profile{metric=\"iscommits\",instance=~\"$Target.*\"}[1m]) or delta(instance_profile{metric=\"isrollbacks\",instance=~\"$Target.*\"}[1m]) or delta(instance_profile{metric=\"pagreads\",instance=~\"$Target.*\"}[1m]) or delta(instance_profile{metric=\"pagwrites\",instance=~\"$Target.*\"}[1m]) or delta(instance_profile{metric=\"plgpagewrites\",instance=~\"$Target.*\"}[1m]) or delta(instance_profile{metric=\"plgwrites\",instance=~\"$Target.*\"}[1m]) or delta(instance_profile{metric=\"llgpagewrites\",instance=~\"$Target.*\"}[1m]) or delta(instance_profile{metric=\"llgwrites\",instance=~\"$Target.*\"}[1m])",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Locks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "lock_profile{metric=\"act_locks\",instance=~\"$Target.*\"}",
     "legendFormat": "{{metric}}"
    },
    {
     "expr": "lock_profile{metric=\"max_locks\",instance=~\"$Target.*\"}",
     "legendFormat": "{{metric}}"
    },
    {
     "expr": "lock_profile{metric=\"wt_locks\",instance=~\"$Target.*\"}",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Buffers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "delta(buff_profile{metric=\"bufreads\",instance=~\"$Target.*\"}[1m])",
     "legendFormat": "{{bufsize}}_{{metric}}"
    },
    {
     "expr": "delta(buff_profile{metric=\"bufwrites\",instance=~\"$Target.*\"}[1m])",
     "legendFormat": "{{bufsize}}_{{metric}}"
    }
   ]
  },
  {
   "title": "Checkpoint Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ckpt_stat{instance=~\"$Target.*\"}",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "DBSpace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "dbs_usage{metric=\"usage\",dbspace!~\"tempdbs.*\",dbspace!~\"llogdbs.*\",dbspace!~\"physdbs.*\",instance=~\"$Target.*\"}",
     "legendFormat": "{{dbspace}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "open_tx_num{instance=~\"$Target.*\"} ",
     "legendFormat": "{{metric}}"
    },
    {
     "expr": "rb_tx_num{instance=~\"$Target.*\"}",
     "legendFormat": "{{metric}}"
    },
    {
     "expr": "wait_mux_num{instance=~\"$Target.*\"}",
     "legendFormat": "{{metric}}"
    },
    {
     "expr": "pre_ltx_num{instance=~\"$Target.*\"}",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Cluster Stat",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cluster_online_node1{instance=~\"$Target.*\"}",
     "legendFormat": "newjsvfdbs001_clusternode-1"
    },
    {
     "expr": "cluster_online_node2{instance=~\"$Target.*\"}",
     "legendFormat": "newjsvfdbs002_clusternode-2"
    },
    {
     "expr": "cluster_online_quorumd{instance=~\"$Target.*\"}",
     "legendFormat": "/dev/block/253:5"
    },
    {
     "expr": "cluster_online_service{instance=~\"$Target.*\"}",
     "legendFormat": "service:informix_newjsvfdbs_cluster"
    }
   ]
  },
  {
   "title": "Logical Log Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "delta(log_usage{instance=~\"$Target.*\"}[1m])",
     "legendFormat": "logsize"
    }
   ]
  },
  {
   "title": "FileSystem Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ifxdir_fsuse{metric!~\"ifxdir_fsuse\",instance=~\"$Target.*\"}",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Connect Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "conn_time{instance=~\"$Target.*\"}",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "Session Buffer Reads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "delta(top_ses{metric=\"bufreads\",instance=~\"$Target.*\"}[1m])>0",
     "legendFormat": "{{sid}}"
    }
   ]
  },
  {
   "title": "Session Buffer Writes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "delta(top_ses{metric=\"bufwrites\",instance=~\"$Target.*\"}[1m])>0",
     "legendFormat": "{{sid}}"
    }
   ]
  },
  {
   "title": "Session  IO Wait Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(top_ses{metric=\"iowaittime\",instance=~\"$Target.*\"}[1m])>0",
     "legendFormat": "{{sid}}"
    }
   ]
  },
  {
   "title": "Session Lock Wait Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(top_ses{metric=\"lockwaittime\",instance=~\"$Target.*\"}[1m])>0",
     "legendFormat": "{{sid}}"
    }
   ]
  },
  {
   "title": "Session Cpu Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(top_ses{metric=\"cpu_time\",instance=~\"$Target.*\"}[1m])>0",
     "legendFormat": "{{sid}}"
    }
   ]
  },
  {
   "title": "SQL TEXT",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 104 },
   "targets": [
    {
     "metrics": [
      {
       "field": "cpu_time",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "select metric" }
       ],
       "settings": { "size": 20 },
       "type": "raw_document"
      }
     ],
     "query": "_index:topsql-$Target-* AND sid:${Session}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Lock",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 114 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 20 },
       "type": "raw_document"
      }
     ],
     "query": "_index:toplock-$Target-* AND seconds_taken:>0",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Page",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 122 },
   "targets": [
    {
     "metrics": [
      {
       "field": "serialv",
       "id": "1",
       "meta": {},
       "settings": { "size": 10 },
       "type": "raw_document"
      }
     ],
     "query": "_index:toppagetable-$Target-*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Extent",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 10, "x": 6, "y": 122 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 10 },
       "type": "raw_document"
      }
     ],
     "query": "_index:topexttable-$Target-*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Serial",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 122 },
   "targets": [
    {
     "expr": "_index:topser*",
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 10 },
       "type": "raw_document"
      }
     ],
     "query": "_index:topserialv-$Target-*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Transaction",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 128 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 5 },
       "type": "raw_document"
      }
     ],
     "query": "_index:toptx-$Target-*",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}